### ISSUE TITLE
Support go modules and tag the project

### ISSUE THREAD

**Issue by rafaeleyng** [opentracing-contrib/go-gin#7]
Currently this project does not use go modules. Also, there is there are no tags to reference it.

We still can use it in projects using go modules by referencing by the commit hash, which is not ideal.

I could add a MR using go modules, but to tag I would need permission.

**Comment by codjust** [comment]
+1

**Comment by stuart-mclaren-hpe** [comment]
Hi, I agree: we should tag and move to go modules.

It may make sense to tag current hash as 1.0.0 and then the modules based release as 2.0.0.

**Comment by rafaeleyng** [comment]
Hey @stuart-mclaren-hpe , just to remind you that now after #8 , you can tag the project and close this issue

**Comment by stuart-mclaren** [comment]
Muito obrigado. Tagged 2.0.0.
