### ISSUE TITLE
Should the version tags follow semantic versioning?

### ISSUE THREAD

**Issue by pandar00** [opentracing-contrib/go-gin#9]
Looks like the tags are missing `v` prefix

As per go module [doc](https://blog.golang.org/publishing-go-modules)
> Every required module in a go.mod has a semantic version, the minimum version of that dependency to use to build the module.

> A semantic version has the form vMAJOR.MINOR.PATCH.

Because of this go module puts an alias v0.0.0 and then hash of the commit of each tag

e.g.
```
$ go get -u github.com/opentracing-contrib/go-gin@1.0.0
go: github.com/opentracing-contrib/go-gin 1.0.0 => v0.0.0-20190301172248-2e18f8b9c7d4
```
This also could confuse some folks who aren't familiar with go versioning and could result in 404 if prefix `v` is specified in `go get`

```
$ go get -u github.com/opentracing-contrib/go-gin@v2.0.0
go get github.com/opentracing-contrib/go-gin@v2.0.0: github.com/opentracing-contrib/go-gin@v2.0.0: invalid version: unknown revision v2.0.0
```

**Comment by stuart-mclaren** [comment]
Thanks for your feedback.

I created a "v2.0.0" release.
